--------------------------------------------------------------------------------
-- File: bank_recon_match_pkg.sql
-- Purpose: Suggest top reconciliation matches for statement lines against
--          AR cash receipts and external transactions.
--
-- Notes:
--   1) This package is defensive by design (caps candidate pool + combination size).
--   2) Supports:
--        - Direct 1:1 match
--        - 2/3 receipt combinations (e.g., 600 + 400)
--        - Repeated/same-amount group match (e.g., 10 x 100 = 1000)
--   3) Use RUN_BATCH to process large data sets (e.g., 30K lines).
--------------------------------------------------------------------------------

-- Optional result table (create once).
-- Stores top-N suggestions for each statement line.
create table xxemr_recon_suggestions (
    suggestion_id           number generated by default on null as identity,
    run_id                  number not null,
    statement_line_id       number not null,
    candidate_rank          number not null,
    candidate_source        varchar2(30) not null, -- RECEIPT_COMBO / RECEIPT_GROUP / EXTERNAL_TXN
    candidate_key           varchar2(2000),        -- IDs list or single txn id
    candidate_amount        number,
    amount_diff             number,
    max_date_diff_days      number,
    reference_score         number,
    final_score             number,
    explanation             varchar2(4000),
    created_at              date default sysdate,
    constraint xxemr_recon_sugg_pk primary key (suggestion_id)
);

create index xxemr_recon_sugg_n1 on xxemr_recon_suggestions(run_id, statement_line_id, candidate_rank);

create or replace package xxemr_bank_recon_pkg as
    procedure suggest_line_matches(
        p_statement_line_id        in  number,
        p_top_n                    in  number   default 3,
        p_date_window_days         in  number   default 15,
        p_amount_tolerance         in  number   default 0,
        p_max_combo_size           in  number   default 3,
        p_max_receipt_pool         in  number   default 60,
        p_include_external_txn     in  varchar2 default 'Y',
        p_allow_one_to_many       in  varchar2 default 'Y',
        p_result                   out sys_refcursor
    );

    procedure run_batch(
        p_run_id                   in  number,
        p_bank_account_id          in  number,
        p_stmt_from_date           in  date,
        p_stmt_to_date             in  date,
        p_top_n                    in  number   default 3,
        p_date_window_days         in  number   default 15,
        p_amount_tolerance         in  number   default 0,
        p_max_combo_size           in  number   default 3,
        p_max_receipt_pool         in  number   default 60,
        p_commit_interval          in  number   default 500
    );

    procedure run_auto(
        p_run_id                   out number,
        p_top_n                    in  number   default 3,
        p_date_window_days         in  number   default 15,
        p_amount_tolerance         in  number   default 0,
        p_max_combo_size           in  number   default 3,
        p_max_receipt_pool         in  number   default 60,
        p_commit_interval          in  number   default 500
    );
end xxemr_bank_recon_pkg;
/

create or replace package body xxemr_bank_recon_pkg as

    procedure suggest_line_matches(
        p_statement_line_id        in  number,
        p_top_n                    in  number,
        p_date_window_days         in  number,
        p_amount_tolerance         in  number,
        p_max_combo_size           in  number,
        p_max_receipt_pool         in  number,
        p_include_external_txn     in  varchar2,
        p_allow_one_to_many       in  varchar2,
        p_result                   out sys_refcursor
    ) is
        l_stmt_amount      xxemr_bank_statement_lines.amount%type;
        l_stmt_date        xxemr_bank_statement_lines.statement_date%type;
        l_bank_account_id  xxemr_bank_statement_lines.bank_account_id%type;
        l_stmt_ref_norm    varchar2(4000);
    begin
        select s.amount,
               trunc(s.statement_date),
               s.bank_account_id,
               regexp_replace(lower(nvl(s.reference_num, '')), '[^a-z0-9]', '')
          into l_stmt_amount,
               l_stmt_date,
               l_bank_account_id,
               l_stmt_ref_norm
          from xxemr_bank_statement_lines s
         where s.statement_line_id = p_statement_line_id;

        open p_result for
            with
            receipt_pool as (
                select *
                from (
                    select r.cash_receipt_id,
                           r.amount,
                           trunc(r.gl_date) gl_date,
                           r.receipt_number,
                           abs(l_stmt_amount - r.amount) amount_diff,
                           abs(trunc(r.gl_date) - l_stmt_date) date_diff,
                           case
                               when l_stmt_ref_norm is null then 0
                               when regexp_replace(lower(nvl(r.receipt_number, '')), '[^a-z0-9]', '') is null then 0
                               else utl_match.edit_distance_similarity(l_stmt_ref_norm, regexp_replace(lower(nvl(r.receipt_number, '')), '[^a-z0-9]', ''))
                           end ref_score,
                           row_number() over (
                               order by
                                   abs(l_stmt_amount - r.amount),
                                   abs(trunc(r.gl_date) - l_stmt_date),
                                   case
                                       when l_stmt_ref_norm is null then 0
                                       when regexp_replace(lower(nvl(r.receipt_number, '')), '[^a-z0-9]', '') is null then 0
                                       else utl_match.edit_distance_similarity(l_stmt_ref_norm, regexp_replace(lower(nvl(r.receipt_number, '')), '[^a-z0-9]', ''))
                                   end desc,
                                   r.cash_receipt_id
                           ) rn
                      from xxemr_ar_cash_receipts r
                     where r.remittance_bank_account_id = l_bank_account_id
                       and trunc(r.gl_date) between l_stmt_date - p_date_window_days and l_stmt_date + p_date_window_days
                       and nvl(r.match_flag, 'N') <> 'Y'
                       and nvl(r.recon_flag, 'N') <> 'Y'
                       and r.status not in ('REVERSED')
                )
                where rn <= p_max_receipt_pool
            ),
            -- Recursive combinations from pool, capped by p_max_combo_size.
            combos (last_rn, combo_size, ids, total_amount, max_date_diff, avg_ref_score) as (
                select rp.rn,
                       1 as combo_size,
                       to_char(rp.cash_receipt_id) as ids,
                       rp.amount as total_amount,
                       rp.date_diff as max_date_diff,
                       rp.ref_score as avg_ref_score
                  from receipt_pool rp
                union all
                select rp.rn,
                       c.combo_size + 1,
                       c.ids || ',' || rp.cash_receipt_id,
                       c.total_amount + rp.amount,
                       greatest(c.max_date_diff, rp.date_diff),
                       ((c.avg_ref_score * c.combo_size) + rp.ref_score) / (c.combo_size + 1)
                  from combos c
                  join receipt_pool rp
                    on rp.rn > c.last_rn
                 where c.combo_size < case when p_allow_one_to_many = 'Y' then p_max_combo_size else 1 end
                   and c.total_amount + rp.amount <= l_stmt_amount + p_amount_tolerance
            ),
            receipt_combo_candidates as (
                select 'RECEIPT_COMBO' candidate_source,
                       ids candidate_key,
                       total_amount candidate_amount,
                       abs(l_stmt_amount - total_amount) amount_diff,
                       max_date_diff max_date_diff_days,
                       round(avg_ref_score, 2) reference_score,
                       round(
                           (100 - least(100, abs(l_stmt_amount - total_amount) / greatest(abs(l_stmt_amount), 1) * 100)) * 0.60 +
                           (100 - least(100, max_date_diff * 100 / greatest(p_date_window_days, 1))) * 0.25 +
                           least(100, avg_ref_score) * 0.15 -
                           (combo_size - 1) * 2,
                           2
                       ) final_score,
                       'Combo size=' || combo_size || ', receipts=' || ids explanation
                  from combos
                 where abs(l_stmt_amount - total_amount) <= p_amount_tolerance
                   and (p_allow_one_to_many = 'Y' or combo_size = 1)
            ),
            -- Special case: many same-amount receipts, e.g. 10 x 100 = 1000.
            receipt_group_candidates as (
                select 'RECEIPT_GROUP' candidate_source,
                       listagg(cash_receipt_id, ',') within group (order by cash_receipt_id) candidate_key,
                       sum(amount) candidate_amount,
                       abs(l_stmt_amount - sum(amount)) amount_diff,
                       max(date_diff) max_date_diff_days,
                       round(avg(ref_score), 2) reference_score,
                       round(
                           (100 - least(100, abs(l_stmt_amount - sum(amount)) / greatest(abs(l_stmt_amount), 1) * 100)) * 0.65 +
                           (100 - least(100, max(date_diff) * 100 / greatest(p_date_window_days, 1))) * 0.20 +
                           least(100, avg(ref_score)) * 0.15,
                           2
                       ) final_score,
                       'Same-amount grouped receipts, cnt=' || count(*) explanation
                  from receipt_pool
                 where p_allow_one_to_many = 'Y'
                 group by amount
                having abs(l_stmt_amount - sum(amount)) <= p_amount_tolerance
                   and count(*) >= 2
            ),
            external_candidates as (
                select 'EXTERNAL_TXN' candidate_source,
                       to_char(e.ext_txn_id) candidate_key,
                       e.amount candidate_amount,
                       abs(l_stmt_amount - e.amount) amount_diff,
                       abs(trunc(e.transaction_date) - l_stmt_date) max_date_diff_days,
                       case
                           when l_stmt_ref_norm is null then 0
                           when regexp_replace(lower(nvl(e.reference_num, '')), '[^a-z0-9]', '') is null then 0
                           else utl_match.edit_distance_similarity(l_stmt_ref_norm, regexp_replace(lower(nvl(e.reference_num, '')), '[^a-z0-9]', ''))
                       end reference_score,
                       round(
                           (100 - least(100, abs(l_stmt_amount - e.amount) / greatest(abs(l_stmt_amount), 1) * 100)) * 0.65 +
                           (100 - least(100, abs(trunc(e.transaction_date) - l_stmt_date) * 100 / greatest(p_date_window_days, 1))) * 0.20 +
                           least(100,
                               case
                                   when l_stmt_ref_norm is null then 0
                                   when regexp_replace(lower(nvl(e.reference_num, '')), '[^a-z0-9]', '') is null then 0
                                   else utl_match.edit_distance_similarity(l_stmt_ref_norm, regexp_replace(lower(nvl(e.reference_num, '')), '[^a-z0-9]', ''))
                               end
                           ) * 0.15,
                           2
                       ) final_score,
                       'External transaction single match' explanation
                  from xxemr_external_transactions e
                 where p_include_external_txn = 'Y'
                   and e.bank_account_id = l_bank_account_id
                   and trunc(e.transaction_date) between l_stmt_date - p_date_window_days and l_stmt_date + p_date_window_days
                   and nvl(e.recon_status, 'UNRECONCILED') not in ('RECONCILED', 'CLEARED')
                   and abs(l_stmt_amount - e.amount) <= p_amount_tolerance
            ),
            all_candidates as (
                select * from receipt_combo_candidates
                union all
                select * from receipt_group_candidates
                union all
                select * from external_candidates
            )
            select *
            from (
                select row_number() over (order by final_score desc, amount_diff, max_date_diff_days) candidate_rank,
                       candidate_source,
                       candidate_key,
                       candidate_amount,
                       amount_diff,
                       max_date_diff_days,
                       reference_score,
                       final_score,
                       explanation
                  from all_candidates
            )
            where candidate_rank <= p_top_n
            order by candidate_rank;
    end suggest_line_matches;

    procedure run_batch(
        p_run_id                   in  number,
        p_bank_account_id          in  number,
        p_stmt_from_date           in  date,
        p_stmt_to_date             in  date,
        p_top_n                    in  number,
        p_date_window_days         in  number,
        p_amount_tolerance         in  number,
        p_max_combo_size           in  number,
        p_max_receipt_pool         in  number,
        p_commit_interval          in  number
    ) is
        cursor c_stmt is
            select s.statement_line_id,
                   nvl(s.external_flag, 'N') external_flag,
                   nvl(s.dashboard_flag, 'N') dashboard_flag
              from xxemr_bank_statement_lines s
             where s.bank_account_id = p_bank_account_id
               and trunc(s.statement_date) between trunc(p_stmt_from_date) and trunc(p_stmt_to_date)
               and nvl(s.match_flag, 'N') <> 'Y'
               and nvl(s.recon_status, 'UNRECONCILED') not in ('RECONCILED', 'CLEARED');

        l_rc           sys_refcursor;
        l_rank         number;
        l_source       varchar2(30);
        l_key          varchar2(2000);
        l_amt          number;
        l_amt_diff     number;
        l_date_diff    number;
        l_ref_score    number;
        l_final_score  number;
        l_expl         varchar2(4000);
        l_count        number := 0;
    begin
        delete from xxemr_recon_suggestions where run_id = p_run_id;

        for r in c_stmt loop
            suggest_line_matches(
                p_statement_line_id    => r.statement_line_id,
                p_top_n                => p_top_n,
                p_date_window_days     => p_date_window_days,
                p_amount_tolerance     => p_amount_tolerance,
                p_max_combo_size       => p_max_combo_size,
                p_max_receipt_pool     => p_max_receipt_pool,
                p_include_external_txn => 'Y',
                p_allow_one_to_many   => case when r.external_flag = 'Y' and r.dashboard_flag = 'Y' then 'N' else 'Y' end,
                p_result               => l_rc
            );

            loop
                fetch l_rc into l_rank, l_source, l_key, l_amt, l_amt_diff, l_date_diff, l_ref_score, l_final_score, l_expl;
                exit when l_rc%notfound;

                insert into xxemr_recon_suggestions (
                    run_id,
                    statement_line_id,
                    candidate_rank,
                    candidate_source,
                    candidate_key,
                    candidate_amount,
                    amount_diff,
                    max_date_diff_days,
                    reference_score,
                    final_score,
                    explanation
                ) values (
                    p_run_id,
                    r.statement_line_id,
                    l_rank,
                    l_source,
                    l_key,
                    l_amt,
                    l_amt_diff,
                    l_date_diff,
                    l_ref_score,
                    l_final_score,
                    l_expl
                );
            end loop;
            close l_rc;

            l_count := l_count + 1;
            if mod(l_count, p_commit_interval) = 0 then
                commit;
            end if;
        end loop;

        commit;
    end run_batch;

    procedure run_auto(
        p_run_id                   out number,
        p_top_n                    in  number,
        p_date_window_days         in  number,
        p_amount_tolerance         in  number,
        p_max_combo_size           in  number,
        p_max_receipt_pool         in  number,
        p_commit_interval          in  number
    ) is
        cursor c_stmt is
            select s.statement_line_id,
                   nvl(s.external_flag, 'N') external_flag,
                   nvl(s.dashboard_flag, 'N') dashboard_flag
              from xxemr_bank_statement_lines s
             where nvl(s.match_flag, 'N') <> 'Y'
               and nvl(s.recon_status, 'UNRECONCILED') not in ('RECONCILED', 'CLEARED')
               and s.bank_account_id is not null;

        l_rc           sys_refcursor;
        l_rank         number;
        l_source       varchar2(30);
        l_key          varchar2(2000);
        l_amt          number;
        l_amt_diff     number;
        l_date_diff    number;
        l_ref_score    number;
        l_final_score  number;
        l_expl         varchar2(4000);
        l_count        number := 0;
    begin
        p_run_id := to_number(to_char(systimestamp, 'YYYYMMDDHH24MISSFF3'));

        delete from xxemr_recon_suggestions where run_id = p_run_id;

        for r in c_stmt loop
            suggest_line_matches(
                p_statement_line_id    => r.statement_line_id,
                p_top_n                => p_top_n,
                p_date_window_days     => p_date_window_days,
                p_amount_tolerance     => p_amount_tolerance,
                p_max_combo_size       => p_max_combo_size,
                p_max_receipt_pool     => p_max_receipt_pool,
                p_include_external_txn => 'Y',
                p_allow_one_to_many   => case when r.external_flag = 'Y' and r.dashboard_flag = 'Y' then 'N' else 'Y' end,
                p_result               => l_rc
            );

            loop
                fetch l_rc into l_rank, l_source, l_key, l_amt, l_amt_diff, l_date_diff, l_ref_score, l_final_score, l_expl;
                exit when l_rc%notfound;

                insert into xxemr_recon_suggestions (
                    run_id,
                    statement_line_id,
                    candidate_rank,
                    candidate_source,
                    candidate_key,
                    candidate_amount,
                    amount_diff,
                    max_date_diff_days,
                    reference_score,
                    final_score,
                    explanation
                ) values (
                    p_run_id,
                    r.statement_line_id,
                    l_rank,
                    l_source,
                    l_key,
                    l_amt,
                    l_amt_diff,
                    l_date_diff,
                    l_ref_score,
                    l_final_score,
                    l_expl
                );
            end loop;
            close l_rc;

            l_count := l_count + 1;
            if mod(l_count, p_commit_interval) = 0 then
                commit;
            end if;
        end loop;

        commit;
    end run_auto;

end xxemr_bank_recon_pkg;
/

--------------------------------------------------------------------------------
-- Example usage
--------------------------------------------------------------------------------
-- Single statement line:
-- var rc refcursor;
-- exec xxemr_bank_recon_pkg.suggest_line_matches(
--         p_statement_line_id    => 123456,
--         p_top_n                => 3,
--         p_date_window_days     => 15,
--         p_amount_tolerance     => 0,
--         p_max_combo_size       => 3,
--         p_max_receipt_pool     => 60,
--         p_include_external_txn => 'Y',
--         p_allow_one_to_many    => 'Y',
--         p_result               => :rc
--      );
-- print rc;
--
-- Batch run for one bank account/date range:
-- exec xxemr_bank_recon_pkg.run_batch(
--         p_run_id            => 20260301,
--         p_bank_account_id   => 1001,
--         p_stmt_from_date    => date '2026-03-01',
--         p_stmt_to_date      => date '2026-03-31',
--         p_top_n             => 3,
--         p_date_window_days  => 15,
--         p_amount_tolerance  => 0,
--         p_max_combo_size    => 3,
--         p_max_receipt_pool  => 60,
--         p_commit_interval   => 500
--      );
--
-- Backend mode (no page-item inputs): auto-read all unreconciled statement lines.
-- declare
--   l_run_id number;
-- begin
--   xxemr_bank_recon_pkg.run_auto(
--       p_run_id            => l_run_id,
--       p_top_n             => 5,
--       p_date_window_days  => 5,
--       p_amount_tolerance  => 10,
--       p_max_combo_size    => 3,
--       p_max_receipt_pool  => 50,
--       p_commit_interval   => 10
--   );
--
--   dbms_output.put_line('Run ID = ' || l_run_id);
-- end;
-- /
